version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"

packages: []

command:
  build:
    - sudo chmod 777 -R /var/www/html
    - composer update
    - npm install



  jekyll: |
    jekyll serve -s /opt/docs -d /var/www/html --drafts --livereload --port 4000 --livereload-port 4100 --host 0.0.0.0

  dev:
   # - webpack build --mode development

  serve:
    - webpack serve --mode development

  setup:
    - git clone git@github.com:kasimirjs/kasi-embed.git workspaces/kasi-embed/

  killall:
    killall jekyll
